<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schedule.proto

namespace ScheduleMicroservice;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ScheduleMicroservice.EntryOptionWithTime</code>
 */
class EntryOptionWithTime extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string cron_time = 1;</code>
     */
    protected $cron_time = '';
    /**
     * Generated from protobuf field <code>string url = 2;</code>
     */
    protected $url = '';
    /**
     * Generated from protobuf field <code>bytes headers = 3;</code>
     */
    protected $headers = '';
    /**
     * Generated from protobuf field <code>bytes body = 4;</code>
     */
    protected $body = '';
    /**
     * Generated from protobuf field <code>int64 next_date = 5;</code>
     */
    protected $next_date = 0;
    /**
     * Generated from protobuf field <code>int64 last_date = 6;</code>
     */
    protected $last_date = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $cron_time
     *     @type string $url
     *     @type string $headers
     *     @type string $body
     *     @type int|string $next_date
     *     @type int|string $last_date
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Schedule::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string cron_time = 1;</code>
     * @return string
     */
    public function getCronTime()
    {
        return $this->cron_time;
    }

    /**
     * Generated from protobuf field <code>string cron_time = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCronTime($var)
    {
        GPBUtil::checkString($var, True);
        $this->cron_time = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string url = 2;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Generated from protobuf field <code>string url = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes headers = 3;</code>
     * @return string
     */
    public function getHeaders()
    {
        return $this->headers;
    }

    /**
     * Generated from protobuf field <code>bytes headers = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setHeaders($var)
    {
        GPBUtil::checkString($var, False);
        $this->headers = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes body = 4;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Generated from protobuf field <code>bytes body = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, False);
        $this->body = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 next_date = 5;</code>
     * @return int|string
     */
    public function getNextDate()
    {
        return $this->next_date;
    }

    /**
     * Generated from protobuf field <code>int64 next_date = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setNextDate($var)
    {
        GPBUtil::checkInt64($var);
        $this->next_date = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 last_date = 6;</code>
     * @return int|string
     */
    public function getLastDate()
    {
        return $this->last_date;
    }

    /**
     * Generated from protobuf field <code>int64 last_date = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLastDate($var)
    {
        GPBUtil::checkInt64($var);
        $this->last_date = $var;

        return $this;
    }

}

