<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schedule.proto

namespace ScheduleMicroservice;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ScheduleMicroservice.PutParameter</code>
 */
class PutParameter extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string identity = 1;</code>
     */
    protected $identity = '';
    /**
     * Generated from protobuf field <code>string time_zone = 2;</code>
     */
    protected $time_zone = '';
    /**
     * Generated from protobuf field <code>bool start = 3;</code>
     */
    protected $start = false;
    /**
     * Generated from protobuf field <code>map<string, .ScheduleMicroservice.EntryOption> entries = 4;</code>
     */
    private $entries;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $identity
     *     @type string $time_zone
     *     @type bool $start
     *     @type array|\Google\Protobuf\Internal\MapField $entries
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Schedule::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string identity = 1;</code>
     * @return string
     */
    public function getIdentity()
    {
        return $this->identity;
    }

    /**
     * Generated from protobuf field <code>string identity = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIdentity($var)
    {
        GPBUtil::checkString($var, True);
        $this->identity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string time_zone = 2;</code>
     * @return string
     */
    public function getTimeZone()
    {
        return $this->time_zone;
    }

    /**
     * Generated from protobuf field <code>string time_zone = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTimeZone($var)
    {
        GPBUtil::checkString($var, True);
        $this->time_zone = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool start = 3;</code>
     * @return bool
     */
    public function getStart()
    {
        return $this->start;
    }

    /**
     * Generated from protobuf field <code>bool start = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setStart($var)
    {
        GPBUtil::checkBool($var);
        $this->start = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, .ScheduleMicroservice.EntryOption> entries = 4;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getEntries()
    {
        return $this->entries;
    }

    /**
     * Generated from protobuf field <code>map<string, .ScheduleMicroservice.EntryOption> entries = 4;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setEntries($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \ScheduleMicroservice\EntryOption::class);
        $this->entries = $arr;

        return $this;
    }

}

