<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: amqp-subscriber.proto

namespace AMQPSubscriber;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>AMQPSubscriber.NoParameter</code>
 */
class NoParameter extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\AmqpSubscriber::initOnce();
        parent::__construct($data);
    }

}

