<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssh.proto

namespace SSHMicroservice;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>SSHMicroservice.TunnelsParameter</code>
 */
class TunnelsParameter extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string identity = 1;</code>
     */
    protected $identity = '';
    /**
     * Generated from protobuf field <code>repeated .SSHMicroservice.TunnelOption tunnels = 2;</code>
     */
    private $tunnels;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $identity
     *     @type \SSHMicroservice\TunnelOption[]|\Google\Protobuf\Internal\RepeatedField $tunnels
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ssh::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string identity = 1;</code>
     * @return string
     */
    public function getIdentity()
    {
        return $this->identity;
    }

    /**
     * Generated from protobuf field <code>string identity = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIdentity($var)
    {
        GPBUtil::checkString($var, True);
        $this->identity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .SSHMicroservice.TunnelOption tunnels = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTunnels()
    {
        return $this->tunnels;
    }

    /**
     * Generated from protobuf field <code>repeated .SSHMicroservice.TunnelOption tunnels = 2;</code>
     * @param \SSHMicroservice\TunnelOption[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTunnels($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \SSHMicroservice\TunnelOption::class);
        $this->tunnels = $arr;

        return $this;
    }

}

