<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssh.proto

namespace SSHMicroservice;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>SSHMicroservice.TunnelOption</code>
 */
class TunnelOption extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string src_ip = 1;</code>
     */
    protected $src_ip = '';
    /**
     * Generated from protobuf field <code>uint32 src_port = 2;</code>
     */
    protected $src_port = 0;
    /**
     * Generated from protobuf field <code>string dst_ip = 3;</code>
     */
    protected $dst_ip = '';
    /**
     * Generated from protobuf field <code>uint32 dst_port = 4;</code>
     */
    protected $dst_port = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $src_ip
     *     @type int $src_port
     *     @type string $dst_ip
     *     @type int $dst_port
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Ssh::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string src_ip = 1;</code>
     * @return string
     */
    public function getSrcIp()
    {
        return $this->src_ip;
    }

    /**
     * Generated from protobuf field <code>string src_ip = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSrcIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->src_ip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 src_port = 2;</code>
     * @return int
     */
    public function getSrcPort()
    {
        return $this->src_port;
    }

    /**
     * Generated from protobuf field <code>uint32 src_port = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setSrcPort($var)
    {
        GPBUtil::checkUint32($var);
        $this->src_port = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string dst_ip = 3;</code>
     * @return string
     */
    public function getDstIp()
    {
        return $this->dst_ip;
    }

    /**
     * Generated from protobuf field <code>string dst_ip = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDstIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->dst_ip = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 dst_port = 4;</code>
     * @return int
     */
    public function getDstPort()
    {
        return $this->dst_port;
    }

    /**
     * Generated from protobuf field <code>uint32 dst_port = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setDstPort($var)
    {
        GPBUtil::checkUint32($var);
        $this->dst_port = $var;

        return $this;
    }

}

